In [27]:
import random
import numpy as np
import pandas as pd
from datetime import date, timedelta


In [6]:
n = int(input("enter the number"))
factors = []
while n%2 ==0:
  n=n//2
  factors.append(2)
i=3
while i*i <= n:
  while n%i ==0:
    factors.append(i)
    n=n//i
  i=i+2
if n > 1:
  factors.append(n)

print(factors)

enter the number70
[2, 5, 7]


In [10]:
arr = np.random.randint(10,100,size=(4,5))
arr

array([[36, 78, 93, 96, 65],
       [86, 75, 28, 78, 13],
       [67, 14, 29, 40, 93],
       [29, 24, 20, 25, 42]])

In [11]:
arr_trans = arr.transpose()
arr_trans

array([[36, 86, 67, 29],
       [78, 75, 14, 24],
       [93, 28, 29, 20],
       [96, 78, 40, 25],
       [65, 13, 93, 42]])

In [13]:
str = input("enter the string")
str_rev = str[::-1]
if str == str_rev:
  print("string is palindrome")
else:
  print("string is not palindrome")

enter the stringpap
string is palindrome


In [16]:
df = pd.read_csv("/content/sample_data/california_housing_test.csv")
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0

In [20]:
text = input("enter the text")
words = 0
word_list = text.split()
words = len(word_list)

print(words)

enter the textmy name is sparsh
4


In [21]:
with open("name.txt",'r') as file:
  content = file.read()
  words = content.split()
  num_words = len(words)
  print(num_words)


11


In [24]:
insertion = input("enter numbers seperated by spaces")
insert_array = np.array(insertion.split(),dtype=int)
print(insert_array)


enter numbers seperated by spaces10 9 8 7 
[10  9  8  7]


In [25]:
def insertion_sort(insert_array):
    for i in range(1, len(insert_array)):
        key = insert_array[i]
        j = i - 1
        while j >= 0 and key < insert_array[j]:
            insert_array[j + 1] = insert_array[j]
            j -= 1
        insert_array[j + 1] = key
    return insert_array

sorted_array = insertion_sort(insert_array)
print("Sorted array:", sorted_array)

Sorted array: [ 7  8  9 10]


In [26]:
num = int(input("enter the number"))
def fibonacci(n):
    if n <= 1:
        return n

    a, b = 0, 1
    for _ in range(2, n + 1):
        a, b = b, a + b
    return b
result = fibonacci(num)
print(result)


enter the number10
55


In [ ]:
def count_sundays(start, end):
    count = 0
    d = start
    while d <= end:
        if d.weekday() == 6:
            count += 1
        d += timedelta(days=1)
    return count

s = date(2023, 1, 1)
e = date(2023, 12, 31)
print(count_sundays(s, e))